### PR TITLE
Basic Login Setup

### PR DESCRIPTION
**Pull request by saikrishnanooka-vl**
## Basic applications setup and login functionality added

### CODE REVIEW

**Review by nels — DISMISSED** [review]

**Comment by nels** [comment]
hi @saikrishnanooka-vl, I am able to run the deploy with _local.yml_ docker-compose file :thumbsup:

However, the _production.yml_ fails because of the django-debug-toolbar:
```
django_1    |     app_config = AppConfig.create(entry)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
django_1    |     module = import_module(entry)
django_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
django_1    |     return _bootstrap._gcd_import(name[level:], package, level)
django_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
django_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
postgres_1  | 2020-07-17 09:27:18.648 UTC [1] LOG:  database system is ready to accept connections
django_1    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
django_1    | ModuleNotFoundError: No module named 'debug_toolbar'
```
We don't want to install the debug-toolbar in production.

Could you please remove the debug-toolbar dependency from production and confirm with:
`$ docker-compose -f production.yml up --build`

**Comment by saikrishnanooka-vl** [comment]
Hi @nels ,
Can you please set DEBUG = FALSE at line 7 in config/settings/local.py and run the production.yml

**Comment by nels** [comment]
> Hi @nels ,
> Can you please set DEBUG = FALSE at line 7 in config/settings/local.py and run the production.yml

hi @saikrishnanooka-vl 
I tried but still getting same error:
```
    django_1    |     module = import_module(entry)  
    django_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module  
    django_1    |     return _bootstrap._gcd_import(name[level:], package, level)  
    django_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import  
    django_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load  
    django_1    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked  
    django_1    | ModuleNotFoundError: No module named 'debug_toolbar'  
```
Will have a look and see if I can find anything

**Comment by nels** [comment]
hi @saikrishnanooka-vl 

I think I found the cause.

The **compose/production/django/start** file calls 
`python /app/manage.py collectstatic --noinput`
before the 
**DJANGO_SETTINGS_MODULE** env variable has been set to  _"config.settings.production"_

The solution is to add
`DJANGO_SETTINGS_MODULE=config.settings.production`
to _.envs/.production/.django_ 

You will also need to add a 
`DJANGO_SECRET_KEY=XYZ`
to the file

**Comment by nels** [comment]
@saikrishnanooka-vl 

`$ docker-compose -f production.yml up`
 now failing with 

```
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
django_1    |     value = self.ENVIRON[var]
django_1    |   File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
django_1    |     raise KeyError(key) from None
django_1    | KeyError: 'REDIS_URL'
django_1    | 
django_1    | During handling of the above exception, another exception occurred:
django_1    | 
django_1    | Traceback (most recent call last):
django_1    |   File "/app/manage.py", line 32, in <module>
django_1    |     execute_from_command_line(sys.argv)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
django_1    |     utility.execute()
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
django_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
django_1    |     settings.INSTALLED_APPS
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
django_1    |     self._setup(name)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
django_1    |     self._wrapped = Settings(settings_module)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
django_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
django_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
django_1    |     return _bootstrap._gcd_import(name[level:], package, level)
django_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
django_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
django_1    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
django_1    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
django_1    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
django_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
django_1    |   File "/app/config/settings/production.py", line 22, in <module>
django_1    |     "LOCATION": env("REDIS_URL"),
django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 123, in __call__
django_1    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
django_1    |     raise ImproperlyConfigured(error_msg)
django_1    | django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable

```
Can you confirm that Redis will be used for this app?
(I don't remember @jonc125 mentioning it)

**Comment by saikrishnanooka-vl** [comment]
> @saikrishnanooka-vl
> 
> `$ docker-compose -f production.yml up`
> now failing with
> 
> ```
> django_1    | Traceback (most recent call last):
> django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
> django_1    |     value = self.ENVIRON[var]
> django_1    |   File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
> django_1    |     raise KeyError(key) from None
> django_1    | KeyError: 'REDIS_URL'
> django_1    | 
> django_1    | During handling of the above exception, another exception occurred:
> django_1    | 
> django_1    | Traceback (most recent call last):
> django_1    |   File "/app/manage.py", line 32, in <module>
> django_1    |     execute_from_command_line(sys.argv)
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
> django_1    |     utility.execute()
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
> django_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
> django_1    |     settings.INSTALLED_APPS
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
> django_1    |     self._setup(name)
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
> django_1    |     self._wrapped = Settings(settings_module)
> django_1    |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
> django_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
> django_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
> django_1    |     return _bootstrap._gcd_import(name[level:], package, level)
> django_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
> django_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
> django_1    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
> django_1    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
> django_1    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
> django_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> django_1    |   File "/app/config/settings/production.py", line 22, in <module>
> django_1    |     "LOCATION": env("REDIS_URL"),
> django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 123, in __call__
> django_1    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
> django_1    |   File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
> django_1    |     raise ImproperlyConfigured(error_msg)
> django_1    | django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable
> ```
> 
> Can you confirm that Redis will be used for this app?
> (I don't remember @jonc125 mentioning it)

No @nels We are not using Redis

**Comment by nels** [comment]
Great, thanks @saikrishnanooka-vl - I'm removing the Redis references
The production settings file contains a lot of AWS settings, are you planning on using AWS for anything?

**Comment by saikrishnanooka-vl** [comment]
> Great, thanks @saikrishnanooka-vl - I'm removing the Redis references
> The production settings file contains a lot of AWS settings, are you planning on using AWS for anything?

image
Hi @nels When I am trying to create project using cookie cutter it is asking to select either Cloud(AWS) or White noise.

**Comment by nels** [comment]
> > Great, thanks @saikrishnanooka-vl - I'm removing the Redis references
> > The production settings file contains a lot of AWS settings, are you planning on using AWS for anything?
> 
> Hi @nels When I am trying to create project using cookie cutter it is asking to select either Cloud(AWS) or White noise.

@saikrishnanooka-vl , I think we should go with Whitenoise if it's for static files

**Review by nels — APPROVED** [review]
Able to deploy using docker-compose with _local.yml_
_production.yml_ requires further configuration for TLS & traefik reverse proxying

**Pull request merged**
